spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: hht500234
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  mail:
    host: smtp.163.com
    username: 13384403671@163.com
    password: HYsFv37sEuAxmDKi
  security:
    jwt:
      key: hht500234
      expire-time: 72
  data:
    redis:
      host: 192.168.108.130
      port: 6379